openapi: 3.0.1
info:
  title: Products API
  description: API to manage products
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    get:
      summary: Get all products
      description: Retrieve a list of all products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
    post:
      summary: Add a new product
      description: Create a new product in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: "#/components/schemas/Product"
  /api/products/{id}:
    get:
      summary: Get product by ID
      description: Retrieve a specific product by its ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the product to retrieve
      responses:
        "200":
          description: A product object
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: "#/components/schemas/Product"
    delete:
      summary: Delete product by ID
      description: Delete a specific product by its ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the product to delete
      responses:
        "200":
          description: Product deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: Product Name
        description:
          type: string
          example: Product Description
        price:
          type: number
          example: 19.99
        stock:
          type: integer
          example: 100
        owner:
          type: string
          example: Owner ID