openapi: 3.0.1
info:
  title: Cart API
  description: API to manage shopping carts
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/carts:
    get:
      summary: Get all carts
      description: Retrieve a list of all shopping carts
      responses:
        "200":
          description: A list of carts
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Cart"
    post:
      summary: Create a new cart
      description: Create a new shopping cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        "201":
          description: Cart created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: "#/components/schemas/Cart"
  /api/carts/{id}:
    get:
      summary: Get cart by ID
      description: Retrieve a specific shopping cart by its ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the cart to retrieve
      responses:
        "200":
          description: A cart object
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: "#/components/schemas/Cart"
    delete:
      summary: Delete cart by ID
      description: Delete a specific cart by its ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the cart to delete
      responses:
        "200":
          description: Cart deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success

components:
  schemas:
    Cart:
      type: object
      properties:
        userId:
          type: string
          example: User ID
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                example: Product ID
              quantity:
                type: integer
                example: 2